feat: add log for secrets

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,6 +11,43 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Check Required Environment Variables
+        run: |
+          required_vars=(
+            "SPRING_PROFILES_ACTIVE"
+            "DB_URL"
+            "DB_USERNAME"
+            "DB_PASSWORD"
+            "REDIS_HOST"
+            "REDIS_PORT"
+            "RABBITMQ_HOST"
+            "RABBITMQ_PORT"
+            "RABBITMQ_USERNAME"
+            "RABBITMQ_PASSWORD"
+            "GOOGLE_CLIENT_ID"
+            "GOOGLE_CLIENT_SECRET"
+            "KAKAO_CLIENT_ID"
+            "KAKAO_CLIENT_SECRET"
+            "KAKAO_REDIRECT_URI"
+            "JWT_ISSUER"
+            "JWT_CLIENT_SECRET"
+            "FRONT_DOMAIN"
+          )
+
+          missing_vars=()
+          for var in "${required_vars[@]}"; do
+            if [ -z "${!var}" ]; then
+              missing_vars+=("$var")
+            fi
+          done
+
+          if [ ${#missing_vars[@]} -ne 0 ]; then
+            echo "::error::Missing required environment variables: ${missing_vars[*]}"
+            exit 1
+          fi
+
+          echo "All required environment variables are set"
+
       - name: Set up JDK 21
         uses: actions/setup-java@v3
         with:
